image:
  file: dxcode/.gitpod.Dockerfile
ports:
  - port: 9888
    onOpen: open-browser
tasks:
  - init: |
      cd dxcode && yarn
      yarn server:init
    command: |
      cd dxcode && gp sync-done init
      export NODE_ENV=development
      export VSCODE_DEV=1
      yarn gulp watch-init
    name: watch app
  - command: |
      cd dxcode && export NODE_ENV=development
      export VSCODE_DEV=1
      gp sync-await init
      ./scripts/code-server.sh  --without-connection-token
    name: run app
    openMode: split-right
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
vscode:
  extensions:
    - dbaeumer.vscode-eslint


# tasks:
#     - name: frontend
#       init: |
#           npm install -g bun && cd apps/www && bun install
#           bun run build
#       command: |
#           bun run dev
    # - name: Nextui
    #   init: |
    #       cd inspirations && cd www && pnpm install
    #       pnpm run build
    #   command: |
    #       pnpm run dev
    # - name: terminalflow-typescript
    #   init: |
    #       cd packages && cd terminalflow && pnpm install
    #       pnpm run typescript
    #   command: |
    #       pnpm run dev
    # - name: terminalflow
    #   init: |
    #       cd packages && cd terminalflow && pnpm install
    #   command: |
    #       pnpm run dev
    # - name: tailwindcss-documentation
    #   init: |
    #       cd inspirations &&
    #       git clone https://github.com/beingofexistence/tailwindcss-documentation.git &&
    #       cd tailwindcss-documentation &&
    #       rm -rf .git
    #   command: |
    #       yarn install &&
    #       yarn run build
    # - name: nextui
    #   init: |
    #       cd inspirations &&
    #       git clone https://github.com/beingofexistence/nextui.git &&
    #       cd nextui &&
    #       rm -rf .git
    # - name: material-ui
    #   init: |
    #       cd inspirations &&
    #       git clone https://github.com/beingofexistence/material-ui.git &&
    #       cd material-ui &&
    #       rm -rf .git
    #   command: |
    #       yarn install
    # - name: nextjs
    #   init: |
    #       cd inspirations &&
    #       git clone https://github.com/vercel/next.js.git &&
    #       cd next.js &&
    #       rm -rf .git
    # - name: WorkSpace
    #   init: |
    #       pnpm install
    #       pnpm run build
    # - name: Terminal
    #   init: |









